### ISSUE TITLE
2021-11-27: Make county in URLs an environment variable

### ISSUE THREAD

**Issue by ejaxon** [CodeWithAsheville/court-notifications#111]
To make it easier to deploy in other NC counties, make the County in the various URLs an environment variable.

**Comment by jayhill** [comment]
In addition to URLs, "Buncombe" appears in `index.html` as well as a bunch of the localized .json files.
I'm not sure how to leverage an environment variable for those. 🤔

**Comment by ejaxon** [comment]
I modified the title to reflect the narrow scope of this one, which is just to make the "100" in URLs that represents Buncombe County an environment variable. I'm going to create a separate issue for the bigger question of how you make it at least relatively easy to customize to a different county. The words Buncombe County show up in multiple places that can't directly use environment variables (translation files being another). In addition, some of the information is BC-specific, e.g., when to show up for District Court vs Admin court vs how Superior Court works.

**Comment by ejaxon** [comment]
Note that there is one place in the client where the 100 code shows up: in the _computeFullSearchUrl_ function - that link needs to be provided by the server.
